import type {
  Activity,
  Cycle,
  Goal,
  PacklistTemplate,
  ShoppingItem,
  Todo,
} from "./types";
import { addDays, todayISO } from "./date";

const T = todayISO();

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    title: "Frühstück bei Tati",
    date: T,
    dateEnd: "",
    time: "09:30",
    place: "Café Tati, Kreuzberg",
    status: "geplant",
    by: "A",
    scope: "geteilt",
    note: "Sonntags-Tradition. Pancakes teilen.",
    icon: "coffee",
    tags: ["freunde"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
  {
    id: "act-2",
    title: "Markt am Maybachufer",
    date: addDays(T, 2),
    dateEnd: "",
    time: "11:00",
    place: "Maybachufer",
    status: "geplant",
    by: "D",
    scope: "geteilt",
    note: "Gemüse für die Woche & Blumen.",
    icon: "leaf",
    tags: ["haushalt"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
  {
    id: "act-3",
    title: "Kino — La Chimera",
    date: addDays(T, 5),
    dateEnd: "",
    time: "20:15",
    place: "Wolf Kino",
    status: "geplant",
    by: "A",
    scope: "geteilt",
    note: "",
    icon: "sparkle",
    tags: ["hobby"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
  {
    id: "act-4",
    title: "Wochenendtrip Wien",
    date: addDays(T, 14),
    dateEnd: addDays(T, 16),
    time: "",
    place: "Wien",
    status: "geplant",
    by: "D",
    scope: "geteilt",
    note: "Lange Wochenende, mit dem Zug. Pension gebucht.",
    icon: "heart",
    tags: ["reise"],
    packlist: [
      { id: "p1", text: "Reisepass", packed: false, scope: "D", by: "D", category: "Dokumente" },
      { id: "p2", text: "Reisepass", packed: false, scope: "A", by: "A", category: "Dokumente" },
      { id: "p3", text: "Ladekabel", packed: false, scope: "geteilt", by: "D", category: "Elektronik" },
      { id: "p4", text: "Powerbank", packed: false, scope: "geteilt", by: "D", category: "Elektronik" },
      { id: "p5", text: "Buch für den Zug", packed: false, scope: "D", by: "D", category: "Sonstiges" },
      { id: "p6", text: "Zahnbürsten", packed: false, scope: "geteilt", by: "A", category: "Hygiene" },
      { id: "p7", text: "Wanderschuhe", packed: false, scope: "D", by: "D", category: "Schuhe" },
      { id: "p8", text: "Regenjacke", packed: false, scope: "geteilt", by: "A", category: "Kleidung" },
    ],
    segments: [
      {
        id: "sg1",
        kind: "train",
        from: "Berlin Hbf",
        to: "Wien Hbf",
        depart: `${addDays(T, 14)}T07:46`,
        arrive: `${addDays(T, 14)}T15:32`,
        ref: "EC 173 · Wagen 24 · Plätze 32/33",
        note: "Restaurant-Wagen vorhanden",
      },
      {
        id: "sg2",
        kind: "train",
        from: "Wien Hbf",
        to: "Berlin Hbf",
        depart: `${addDays(T, 16)}T16:28`,
        arrive: `${addDays(T, 17)}T00:15`,
        ref: "Nightjet NJ 456 · Liegewagen",
        note: "",
      },
    ],
    preTripShopping: [
      { id: "pt1", text: "Snacks für den Zug", done: false, scope: "geteilt", by: "D" },
      { id: "pt2", text: "Sonnencreme nachfüllen", done: false, scope: "geteilt", by: "A" },
      { id: "pt3", text: "Bargeld abheben", done: false, scope: "D", by: "D" },
    ],
  },
  {
    id: "act-5",
    title: "Bücher tauschen im Cargo",
    date: "",
    dateEnd: "",
    time: "",
    place: "Cargo Books",
    status: "idee",
    by: "A",
    scope: "geteilt",
    note: "",
    icon: "book",
    tags: ["hobby"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
  {
    id: "act-6",
    title: "Telefonat mit Lukas",
    date: addDays(T, 1),
    dateEnd: "",
    time: "17:00",
    place: "",
    status: "geplant",
    by: "D",
    scope: "D",
    note: "Geburtstagsplanung.",
    icon: "house",
    tags: ["familie"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
  {
    id: "act-7",
    title: "Stand-up & Sprint-Review",
    date: addDays(T, 1),
    dateEnd: "",
    time: "09:00",
    place: "Office / Remote",
    status: "geplant",
    by: "D",
    scope: "D",
    note: "",
    icon: "book",
    tags: ["arbeit"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
  {
    id: "act-8",
    title: "Yoga mit Sara",
    date: addDays(T, -2),
    dateEnd: "",
    time: "18:30",
    place: "Studio Mitte",
    status: "geplant",
    by: "A",
    scope: "A",
    note: "verpasst — verschoben?",
    icon: "heart",
    tags: ["gesundheit"],
    packlist: [],
    segments: [],
    preTripShopping: [],
  },
];

const now = Date.now();

export const SEED_SHOPPING: ShoppingItem[] = [
  { id: "s-1", text: "Tomaten (San Marzano)", done: false, by: "A", scope: "geteilt", spinnerei: false, qty: "1 Dose", category: "lebensmittel", addedAt: now - 1000 * 60 * 60 * 2 },
  { id: "s-2", text: "Sauerteigbrot", done: false, by: "D", scope: "geteilt", spinnerei: false, qty: "", category: "lebensmittel", addedAt: now - 1000 * 60 * 60 * 5 },
  { id: "s-3", text: "Olivenöl", done: false, by: "A", scope: "geteilt", spinnerei: false, qty: "groß", category: "lebensmittel", addedAt: now - 1000 * 60 * 60 * 26 },
  { id: "s-4", text: "Zahnpasta", done: false, by: "A", scope: "geteilt", spinnerei: false, qty: "", category: "drogerie", addedAt: now - 1000 * 60 * 60 * 48 },
  { id: "s-5", text: "Waschmittel Sensitiv", done: false, by: "D", scope: "geteilt", spinnerei: false, qty: "", category: "drogerie", addedAt: now - 1000 * 60 * 60 * 24 },
  { id: "s-6", text: "Notizbuch Leuchtturm", done: false, by: "A", scope: "A", spinnerei: false, qty: "A5 dotted", category: "sonstiges", addedAt: now - 1000 * 60 * 60 * 3 },
  { id: "s-7", text: "Schmaler schwarzer Pulli", done: false, by: "D", scope: "D", spinnerei: true, qty: "", category: "sonstiges", addedAt: now - 1000 * 60 * 60 * 72 },
  { id: "s-8", text: "Plattenspieler", done: false, by: "A", scope: "geteilt", spinnerei: true, qty: "", category: "sonstiges", addedAt: now - 1000 * 60 * 60 * 120 },
  { id: "s-9", text: "Kaffee gemahlen", done: true, by: "D", scope: "geteilt", spinnerei: false, qty: "", category: "lebensmittel", addedAt: now - 1000 * 60 * 60 * 30 },
];

export const SEED_TODOS: Todo[] = [
  { id: "t-1", text: "Steuererklärung abschicken", done: false, due: addDays(T, -2), prio: "hoch", by: "A", scope: "A", addedAt: now - 1000 * 60 * 60 * 96, note: "", tags: ["finanzen"] },
  { id: "t-2", text: "Müll rausbringen", done: false, due: T, prio: "normal", by: "D", scope: "geteilt", addedAt: now - 1000 * 60 * 60 * 8, note: "", tags: ["haushalt"] },
  { id: "t-3", text: "Anruf Hausverwaltung", done: false, due: addDays(T, 1), prio: "normal", by: "A", scope: "geteilt", addedAt: now - 1000 * 60 * 60 * 12, note: "wegen Heizung im Bad", tags: ["haushalt"] },
  { id: "t-4", text: "Geschenk für Mama", done: false, due: addDays(T, 4), prio: "hoch", by: "D", scope: "D", addedAt: now - 1000 * 60 * 60 * 24, note: "", tags: ["familie"] },
  { id: "t-5", text: "Bibliothek: Bücher zurück", done: false, due: addDays(T, 6), prio: "tief", by: "A", scope: "geteilt", addedAt: now - 1000 * 60 * 60 * 60, note: "", tags: ["hobby"] },
  { id: "t-6", text: "Yoga-Termin verschieben", done: false, due: "", prio: "tief", by: "A", scope: "A", addedAt: now - 1000 * 60 * 60 * 10, note: "", tags: ["gesundheit"] },
  { id: "t-7", text: "Pflanzen gießen", done: true, due: addDays(T, -1), prio: "normal", by: "D", scope: "geteilt", addedAt: now - 1000 * 60 * 60 * 26, note: "", tags: ["haushalt"] },
  { id: "t-8", text: "Code-Review Jonas", done: false, due: T, prio: "hoch", by: "D", scope: "D", addedAt: now - 1000 * 60 * 60 * 4, note: "PR #432, Auth-Refactor", tags: ["arbeit"] },
  { id: "t-9", text: "Sprint-Planning vorbereiten", done: false, due: addDays(T, 1), prio: "normal", by: "D", scope: "D", addedAt: now - 1000 * 60 * 60 * 6, note: "", tags: ["arbeit"] },
];

export const SEED_GOALS: Goal[] = [
  {
    id: "g-1",
    title: "Sparen für Sommerreise Portugal",
    term: "mittel",
    target: 2400,
    current: 1350,
    unit: "€",
    by: "A",
    scope: "geteilt",
    steps: [
      { id: "g1s1", text: "Reiseziele engere Auswahl", done: true },
      { id: "g1s2", text: "Flug-Preise tracken", done: true },
      { id: "g1s3", text: "Unterkunft Lissabon recherchieren", done: false },
      { id: "g1s4", text: "Mietwagen vs. Zug entscheiden", done: false },
    ],
  },
  {
    id: "g-2",
    title: "3× pro Woche laufen",
    term: "kurz",
    target: 12,
    current: 7,
    unit: "Läufe",
    by: "D",
    scope: "D",
    steps: [
      { id: "g2s1", text: "Schuhe wieder rausstellen", done: true },
      { id: "g2s2", text: "Lauf-Playlist machen", done: true },
      { id: "g2s3", text: "Sonntag 10k", done: false },
    ],
  },
  {
    id: "g-3",
    title: "Eigene Wohnung mit Garten",
    term: "lang",
    target: 100,
    current: 18,
    unit: "%",
    by: "A",
    scope: "geteilt",
    steps: [
      { id: "g3s1", text: "Budget-Plan erstellen", done: true },
      { id: "g3s2", text: "Banken vergleichen", done: false },
      { id: "g3s3", text: "Gebiete eingrenzen", done: false },
    ],
  },
  {
    id: "g-4",
    title: "Wöchentlich Italienisch üben",
    term: "kurz",
    target: 20,
    current: 9,
    unit: "Wochen",
    by: "D",
    scope: "geteilt",
    steps: [
      { id: "g4s1", text: "Duolingo täglich", done: true },
      { id: "g4s2", text: "Tandem-Partner finden", done: false },
    ],
  },
];

export const SEED_CYCLE: Cycle = {
  owner: "A",
  scope: "geteilt",
  avgCycle: 29,
  avgPeriod: 5,
  periodStarts: [addDays(T, -42), addDays(T, -13)],
  entries: {
    [addDays(T, -13)]: { flow: 3, mood: "weich", energy: 2, symptoms: ["krämpfe", "müde"], note: "" },
    [addDays(T, -12)]: { flow: 2, mood: "okay", energy: 3, symptoms: ["krämpfe"], note: "" },
    [addDays(T, -11)]: { flow: 1, mood: "klar", energy: 3, symptoms: [], note: "" },
    [addDays(T, -2)]: { mood: "energisch", energy: 5, symptoms: [], note: "lange spaziert" },
    [addDays(T, -1)]: { mood: "fokussiert", energy: 4, symptoms: [], note: "" },
  },
};

export const SEED_PACKLIST_TEMPLATES: PacklistTemplate[] = [
  {
    id: "tpl-wochenende",
    name: "Wochenende",
    by: "D",
    scope: "geteilt",
    items: [
      { id: "tpl-w-1", text: "Zahnbürste & Zahnpasta", scope: "geteilt", category: "Hygiene" },
      { id: "tpl-w-2", text: "Wechselkleidung", scope: "D", category: "Kleidung" },
      { id: "tpl-w-3", text: "Wechselkleidung", scope: "A", category: "Kleidung" },
      { id: "tpl-w-4", text: "Ladekabel", scope: "geteilt", category: "Elektronik" },
      { id: "tpl-w-5", text: "Powerbank", scope: "geteilt", category: "Elektronik" },
      { id: "tpl-w-6", text: "Buch", scope: "D", category: "Sonstiges" },
      { id: "tpl-w-7", text: "Buch", scope: "A", category: "Sonstiges" },
      { id: "tpl-w-8", text: "Pyjama", scope: "D", category: "Kleidung" },
      { id: "tpl-w-9", text: "Pyjama", scope: "A", category: "Kleidung" },
    ],
  },
  {
    id: "tpl-wandern",
    name: "Wandern / Outdoor",
    by: "D",
    scope: "geteilt",
    items: [
      { id: "tpl-h-1", text: "Wanderschuhe", scope: "D", category: "Schuhe" },
      { id: "tpl-h-2", text: "Wanderschuhe", scope: "A", category: "Schuhe" },
      { id: "tpl-h-3", text: "Regenjacke", scope: "geteilt", category: "Kleidung" },
      { id: "tpl-h-4", text: "Wasserflasche", scope: "geteilt", category: "Outdoor" },
      { id: "tpl-h-5", text: "Müsliriegel / Snacks", scope: "geteilt", category: "Snacks" },
      { id: "tpl-h-6", text: "Sonnencreme", scope: "geteilt", category: "Hygiene" },
      { id: "tpl-h-7", text: "Erste-Hilfe-Set", scope: "geteilt", category: "Outdoor" },
      { id: "tpl-h-8", text: "Karte / GPS", scope: "geteilt", category: "Outdoor" },
    ],
  },
  {
    id: "tpl-strand",
    name: "Strand",
    by: "A",
    scope: "geteilt",
    items: [
      { id: "tpl-s-1", text: "Badesachen", scope: "A", category: "Kleidung" },
      { id: "tpl-s-2", text: "Badesachen", scope: "D", category: "Kleidung" },
      { id: "tpl-s-3", text: "Handtuch", scope: "A", category: "Sonstiges" },
      { id: "tpl-s-4", text: "Handtuch", scope: "D", category: "Sonstiges" },
      { id: "tpl-s-5", text: "Sonnencreme LSF 50", scope: "geteilt", category: "Hygiene" },
      { id: "tpl-s-6", text: "Strohhut", scope: "A", category: "Kleidung" },
      { id: "tpl-s-7", text: "Buch", scope: "geteilt", category: "Sonstiges" },
      { id: "tpl-s-8", text: "Wasserflasche", scope: "geteilt", category: "Outdoor" },
    ],
  },
  {
    id: "tpl-flug",
    name: "Flugreise (Handgepäck)",
    by: "A",
    scope: "geteilt",
    items: [
      { id: "tpl-f-1", text: "Reisepass / Ausweis", scope: "A", category: "Dokumente" },
      { id: "tpl-f-2", text: "Reisepass / Ausweis", scope: "D", category: "Dokumente" },
      { id: "tpl-f-3", text: "Boarding-Pass / Tickets", scope: "geteilt", category: "Dokumente" },
      { id: "tpl-f-4", text: "Ladekabel + Adapter", scope: "geteilt", category: "Elektronik" },
      { id: "tpl-f-5", text: "Kopfhörer", scope: "A", category: "Elektronik" },
      { id: "tpl-f-6", text: "Kopfhörer", scope: "D", category: "Elektronik" },
      { id: "tpl-f-7", text: "Wasserflasche (leer)", scope: "geteilt", category: "Sonstiges" },
      { id: "tpl-f-8", text: "Snack", scope: "geteilt", category: "Snacks" },
    ],
  },
];
